
import React from 'react';
import { Button } from '@/components/ui/button';
import { useNotificationsContext } from '@/context/NotificationsContext';
import notificationService from '@/utils/notificationService';
import { MessageSquare, Bell, AlertTriangle, Info, Check } from 'lucide-react';

const NotificationDemo: React.FC = () => {
  const { notifications } = useNotificationsContext();
  
  const handleAddLocalNotification = (type: 'info' | 'success' | 'warning' | 'error') => {
    const title = `${type.charAt(0).toUpperCase() + type.slice(1)} Notification`;
    const message = `This is a ${type} notification generated by the local component at ${new Date().toLocaleTimeString()}`;
    
    notifications.addNotification(title, message, {
      showToast: true,
      type,
      actionUrl: type === 'success' ? 'https://example.com/details' : undefined
    });
  };
  
  const handleAddGlobalNotification = () => {
    notificationService.broadcast({
      id: `global-${Date.now()}`,
      title: 'System Notification',
      message: 'This is a global notification sent via the notification service',
      date: new Date(),
      read: false,
      type: 'info'
    });
  };
  
  return (
    <div className="p-4 border rounded-lg mb-6">
      <h3 className="text-lg font-semibold mb-4">Notification System Demo</h3>
      
      <div className="flex flex-wrap gap-2">
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => handleAddLocalNotification('info')}
        >
          <Info className="h-4 w-4 mr-2 text-blue-500" />
          Add Info
        </Button>
        
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => handleAddLocalNotification('success')}
        >
          <Check className="h-4 w-4 mr-2 text-green-500" />
          Add Success
        </Button>
        
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => handleAddLocalNotification('warning')}
        >
          <AlertTriangle className="h-4 w-4 mr-2 text-yellow-500" />
          Add Warning
        </Button>
        
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => handleAddLocalNotification('error')}
        >
          <AlertTriangle className="h-4 w-4 mr-2 text-red-500" />
          Add Error
        </Button>
        
        <Button 
          variant="default" 
          size="sm" 
          onClick={handleAddGlobalNotification}
        >
          <Bell className="h-4 w-4 mr-2" />
          Global Broadcast
        </Button>
        
        <Button 
          variant="destructive" 
          size="sm" 
          onClick={notifications.clearAllNotifications}
        >
          Clear All
        </Button>
      </div>
      
      <div className="mt-4 text-sm text-muted-foreground">
        <p>Unread: {notifications.unreadCount} / Total: {notifications.notifications.length}</p>
      </div>
    </div>
  );
};

export default NotificationDemo;
